### ISSUE TITLE
Deleting and renaming predefined scenes not possible

### ISSUE THREAD

**Issue by aauEnvisage** [DigiArt-project/WordpressUnity3DEditor#111] opened 2017-08-31 12:24 UTC
Is this a feature or a bug?

**Comment by jimver04** [comment] 2017-09-01 06:57
Deleting will be ready today.
Editing is not completed yet

**Comment by tpapaz** [comment] 2017-09-01 07:10
@jimver04 -> Correction: Edit is working. (the title has been updated)

**Comment by tpapaz** [comment] 2017-09-01 07:22
Hello @aauEnvisage, it is crucial for the platform that the predefined scenes cannot be deleted. It's a feature :)

We haven't decided yet on the rename functionality, standby.

**Comment by aauEnvisage** [comment] 2017-09-05 13:32
Okay, it's a feature then :)

**Comment by tpapaz** [comment] 2017-09-08 09:56
Possible duplicate of #112

**Comment by tpapaz** [comment] 2017-09-08 09:57
@aauEnvisage We are implementing title & description renaming. Delete action is solidified as a no-no. :)
Closing the issue, we can keep track of it in #112.

**Closed** 2017-09-08 09:58 UTC
Labels: bug
